/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2S.h"
#include "I2S_PVT.h"
#include "P3_0_aliases.h"
#include "P3_0.h"
#include "isr_i2s_tx.h"
#include "isr_i2s_rx.h"
#include "Clock_1.h"
#include "ADC.h"
#include "DAC.h"
#include "ADC_IN_aliases.h"
#include "ADC_IN.h"
#include "isr_adc_eoc.h"
#include "DAC_OUT_aliases.h"
#include "DAC_OUT.h"
#include "OUT_ADC_INT_aliases.h"
#include "OUT_ADC_INT.h"
#include "OUT_I2S_WS_aliases.h"
#include "OUT_I2S_WS.h"
#include "SW2_aliases.h"
#include "SW2.h"
#include "SW3_aliases.h"
#include "SW3.h"
#include "P3_3_aliases.h"
#include "P3_3.h"
#include "P3_1_aliases.h"
#include "P3_1.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

